apiVersion: v1
kind: ConfigMap
metadata:
  name: bugsathi-config
  namespace: bugsathi
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  HTTP_ADDR: ":8080"
  WORKER_HTTP_ADDR: ":8081"
  POSTGRES_HOST: "postgres.bugsathi.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "bugsathi"
  POSTGRES_DB: "bugsathi"
  POSTGRES_SSLMODE: "disable"
  MINIO_ENDPOINT: "minio.bugsathi.svc.cluster.local:9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: "bugsathi"
  KAFKA_BROKERS: "redpanda.bugsathi.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "bugsathi"
  AI_PROVIDER: "mock"
  AUTH_ACCESS_TTL: "15m"
  AUTH_REFRESH_TTL: "168h"
